name       : libunibreak
version    : '5.1'
release    : 4
source     :
    - https://github.com/adah1972/libunibreak/releases/download/libunibreak_5_1/libunibreak-5.1.tar.gz : dd1a92d4c5646aa0e457ff41d89812ec5243863be6c20bbcb5ee380f3dd78377
license    : Zlib
component  : programming.library
summary    : Unibreak Library
description: |
    An implementation of the line breaking and word breaking algorithms as described in Unicode Standard Annex 14 and Unicode Standard Annex 29.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
