name       : libunibreak
version    : 3.0
release    : 2
source     :
    - https://github.com/adah1972/libunibreak/archive/libunibreak_3_0.tar.gz : 2b3f6bfe011f16240e5fa737888b04a58fff17c6295c252a7275b3879c0dbe1f
license    :
    - Zlib
    - Libpng
component  : programming.library
summary    : Unibreak Library
description: |
    An implementation of the line breaking and word breaking algorithms as described in Unicode Standard Annex 14 and Unicode Standard Annex 29.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
