name       : libunibreak
version    : '5.0'
release    : 3
source     :
    - https://github.com/adah1972/libunibreak/releases/download/libunibreak_5_0/libunibreak-5.0.tar.gz : 58f2fe4f9d9fc8277eb324075ba603479fa847a99a4b134ccb305ca42adf7158
license    : Zlib
component  : programming.library
summary    : Unibreak Library
description: |
    An implementation of the line breaking and word breaking algorithms as described in Unicode Standard Annex 14 and Unicode Standard Annex 29.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
